Category.create!(name: "American", priority: "2")
Category.create!(name: "Caribbean", priority: "4")
Category.create!(name: "Chinese", priority: "6")
Category.create!(name: "French", priority: "1")
Category.create!(name: "Italian", priority: "3")
Category.create!(name: "Mexican", priority: "5")
